apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-httpd
  name: deploy-httpd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 25%
  selector:
    matchLabels:
      run: pod-httpd-2
  template:
    metadata:
      labels:
        run: pod-httpd-2
      name: pod-httpd
    spec:
      containers:
      - image: httpd:alpine
        name: pod-httpd
        
