apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"deploy-httpd"},"name":"deploy-httpd","namespace":"default"},"spec":{"replicas":4,"selector":{"matchLabels":{"run":"pod-httpd-2"}},"template":{"metadata":{"labels":{"run":"pod-httpd-2"},"name":"pod-httpd"},"spec":{"containers":[{"image":"httpd","name":"pod-httpd"}]}}}}
    creationTimestamp: "2024-04-28T15:32:58Z"
    generation: 2
    labels:
      app: deploy-httpd
    name: deploy-httpd
    namespace: default
    resourceVersion: "142290"
    uid: 3e603a8f-670c-46dd-84dc-2889204eb7e1
  spec:
    progressDeadlineSeconds: 600
    replicas: 5
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: pod-httpd-2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: pod-httpd-2
        name: pod-httpd
      spec:
        containers:
        - image: httpd
          imagePullPolicy: Always
          name: pod-httpd
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 4
    conditions:
    - lastTransitionTime: "2024-04-28T15:33:22Z"
      lastUpdateTime: "2024-04-28T15:33:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-04-28T15:32:58Z"
      lastUpdateTime: "2024-04-28T15:33:22Z"
      message: ReplicaSet "deploy-httpd-57f574c688" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 4
    replicas: 4
    updatedReplicas: 4
kind: List
metadata:
  resourceVersion: ""
