apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-httpd
  name: httpd-svc
spec:
  selector:
    run: pod-httpd-2
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31100
  
  

