apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-httpd
  name: httpd-svc
spec:
  selector:
    run: pod-httpd-2
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31101
  
status:
  loadBalancer: {}
